spring:
  application:
    name: franchise-management-api


aws:
  access-key: ${AWS_ACCESS_KEY:test-access-key}
  secret-key: ${AWS_SECRET_KEY:test-secret-key}
  region: ${AWS_REGION:us-east-2}
  dynamodb:
    table-name: ${DYNAMODB_TABLE_NAME:Franchise}
